name: Translate book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
      
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  typos-check:
    name: Spell Check with Typos
    runs-on: colab
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
        with:
          repository: "yihong0618/bilingual_book_maker"
          ref: "main"
          path: "${{ github.workspace }}"
      - name: Check spelling with custom config file
        uses: crate-ci/typos@v1.16.6
        with:
          config: ./typos.toml
  testing:
    strategy:
      matrix:  
        include:
          - link_folder: https://share.smbcat.workers.dev/2:/books
            book_name: the_little_prince
            book_type: txt
    runs-on: ubuntu-latest
    steps:
      - 
        name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - 
        name: Checkout github
        uses: actions/checkout@v4
        with:
          repository: "yihong0618/bilingual_book_maker"
          ref: "main"
          path: "${{ github.workspace }}"
      - 
        name: Install python 3.9 
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - 
        name: Check formatting and install requirements
        run: |
            pip install black
            black . --check        
            pip install -r requirements.txt           
      - 
        name: Download book
        run: wget "${{ matrix.link_folder }}/${{ matrix.book_name }}.${{ matrix.book_type }}"
      - 
        name: Translate book
        run: python3 make_book.py --book_name ${{ matrix.book_name }}.${{ matrix.book_type }} --model gemini --gemini_key ${{ secrets.GEMINI_API_KEY }}  --language vi        
      - 
        name: Rename and upload book
        if: env.GEMINI_API_KEY != null
        uses: actions/upload-artifact@v4
        with:
          name: epub_output
          path: ${{ matrix.book_name }}_bilingual.${{ matrix.book_type }}
